spring:
  application:
    name: rabbitmq-binder
  cloud:
    stream:
      function:
        definition: myProducerSource;myConsumerSink
      bindings:
        myProducer-out-0:
         destination: my-topic
        myConsumer-in-0:
          destination: my-topic
      poller:
        fixed-delay: 500