services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=user-db
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=1234