services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./mysql:/var/lib/mysql 
# docker compose -f docker-compose2.yml up -d