# spring.application.name=consumer-service-binder

# spring.cloud.stream.bindings.input.destination=myTopic
# spring.cloud.stream.bindings.input.content-type=application/json

# server.port=8081
# management.endpoints.jmx.exposure.include=*

spring:
  application:
    name: consumer-service-binder
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        input:
          destination: example-exchange
          group: consumer-group
server:
  port: 8081